import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'TrackApp',
  description: 'Generated by create next app'
}

export default function Home() {
  return <div>Hello</div>
}
